<h2 style="color:navy"><u>Practical : 2</u></h2>

****<h4><u>Write a NumPy program to implement following operation</u></h4>****

* to convert a list of numeric values into a one-dimensional NumPy
array

In [1]:
import numpy as np;

arr = np.array([10,20,30,40,50])
print("One Dimensional Array: \n",arr)

One Dimensional Array: 
 [10 20 30 40 50]


* to create a 3x3 matrix with values ranging from 2 to 10

In [2]:
import numpy as np;

arr = np.arange(2, 11).reshape(3,3)
print("3x3 Matrix ranging from 2 to 10: \n",arr)

3x3 Matrix ranging from 2 to 10: 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


* to append values at the end of an array

In [3]:
import numpy as np;

arr = np.array(["a","b","c"])
arr = np.append(arr, ["d"])
print("Append items in array: \n",arr)

Append items in array: 
 ['a' 'b' 'c' 'd']


* to create another shape from an array without changing its data(3*2
to 2*3)

In [4]:
import numpy as np;

arr = np.array([10,20,30,40,50,60])

arr_3x2 = np.reshape(arr,(3,2))
arr_2x3 = np.reshape(arr,(2,3))

print("3x2 Array: \n",arr_3x2)
print("2x3 Array: \n",arr_2x3)

3x2 Array: 
 [[10 20]
 [30 40]
 [50 60]]
2x3 Array: 
 [[10 20 30]
 [40 50 60]]
